version: '2'
services:
  my-flow-postgresql:
    image: docker-registry.pico-pfc.dev.echonet/postgres:10.4
    volumes:
      - ~/volumes/jhipster/App/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=App
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
